name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests within docker container
      run: docker build . --file Dockerfile
